import type { Metadata } from "next";
import { Geist, Geist_Mono, League_Spartan } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";




const spartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
   <body className={`${spartan.variable} antialiased bg-[var(--color-background)] text-[var(--color-foreground)] transition-colors`}>
  <div className="flex flex-col md:flex-row min-h-screen">
    <Sidebar />
    <main className="flex-1">{children}</main>
  </div>
</body>

    </html>

  );
}
