import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono, League_Spartan } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import ClientLayoutWrapper from '@/components/ClientLayoutWrapper';




const spartan = League_Spartan({
  variable: "--font-league-spartan",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>)


{
 
  return (

    <html lang="en">
      <body className={`${spartan.variable} antialiased bg-[var(--color-background)] text-[var(--color-foreground)] transition-colors`}>
        <ClientLayoutWrapper>
          {children}
        </ClientLayoutWrapper>
      </body>
    </html>

  );
}
